dist: trusty
sudo: required
notifications:
  email: false
language:
- cpp
compiler:
- gcc
#- clang
addons:
  sonarcloud:
    organization: "lkeegan-github"
    token:
      secure: HWHr4NAS6nFgc1jNN57DtXyt+/59fCCq3dWY96yshRIYs/hVZD1JBUlMM4WQVCTtxceQnAyR8dtE3hhsKABJqO9QpXOSgb1750EEqNG1kZcqJ1pLoFOuDjbJEuPhM9AYtBI/zbSwJPZxsUZCsF/xdelCX3ja0epgSneDwIRHDKXyc1PrbyBk8MWg4vM/BfvgH89j4VTpoebpbN/4/oHvrkzYytIPt9lTfiy3hwKMeFnUoCpjXoxruOdXrI0UMZuKuVm+DkMb51x8A0Ipmz/RFCOFcXWAmpVijBFoGE6lgcLNrPuBNnf/iSWCmrqHmRrvgagM3vOgXonqaKcfoezZ0MoY8XwBRXo/ttBqZKMAsxst9UsKsZe54vybm95QZCLniWL0mn2c/KElZsKo5IRz4uzXgoscQojBxKu1RHDyxPlaFht+Gxp5BX8F3+vks0WhBUp9SRphXSy9wuElw3GzCGJPfCM9eq5TKivna9IJvfGKoD7U6pXHQf3y+VFWRT0XEANSbn1SBp6srl48A8dKyX3syVJlEHhhG3G4bUNLPWFHOvJfaPf/3a53lQZ8xbo0Iwioru00fHcDOCr3z9q04qRwP7trii0hIsdQyDib9G3XhJAvfuE37ZBlfQmjj0wOL1dGhUvoJ8Vvz2lq9+GUGwe+l3U7Fe/K06Nt0sigdXg=
  apt:
    packages:
    - lcov
    - valgrind
script:
- export OMP_NUM_THREADS=2
# install google benchmark library
- git clone https://github.com/google/benchmark.git google-benchmark
- cd google-benchmark
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_ENABLE_GTEST_TESTS=OFF
- make -j2
- sudo make install
# debug compilation
- cd ../../
- mkdir Debug
- cd Debug
- cmake -DCMAKE_BUILD_TYPE=Debug ..
# Wraps the compilation with the Build Wrapper to generate configuration (used
# later by the SonarQube Scanner) into the "bw-output" folder
- build-wrapper-linux-x86-64 --out-dir ../bw-output make -j2
# run tests through valgrind
# - valgrind ./tests -d yes
- cd ../
# release compilation
- mkdir Release
- cd Release
- cmake -DCMAKE_BUILD_TYPE=Release .. && make -j2
- valgrind ./tests -d yes
- ./benchmark
- cd ../
after_success:
# gcov files for sonarcloud.io
- mkdir gcov
- cd gcov
- gcov -p ../Debug/CMakeFiles/tests.dir/*/*.gcno
- cd ../
- sonar-scanner
# lcov .info file for codecov.io
- cd Debug
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info 'catch/*' '/usr/*' '*/catch/*' '*/test/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -X gcov -f "coverage.info"
